name: infrastructure-pipeline

on:
  push:
    branches: [xx] # change to main or desidered branch
    tags: ['v*']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  AWS_REGION: eu-west-2
  TF_BACKEND_BUCKET: terraform-state-department-name
  TF_BACKEND_KEY: terraform.tfstate
  TF_DYNAMODB_TABLE: terraform-lock-table
  TF_PROJECT_NAME: project-name
  ENV: ${{ inputs.environment }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy infra to ${{ github.event.inputs.environment }} environment
    uses: ./.github/workflows/deploy_infrastructure.yml
    secrets: inherit
    with:
      environment: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && 'prod' || github.event.inputs.environment }}
